# The URL the site will be built for
base_url = "/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "terminimal"

title = "Rukai"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
accent_color = "red-auto"
background_color = ""
copyright_html = " "
logo_text = "Rukai"
use_full_hack_font = true
enable_post_view_navigation = false
page_titles = "page_only"

menu_items = [
    # tags should only be enabled if you have "tags" taxonomy
    # see documentation below for more details
    {name = "DPedal", url = "/dpedal"},
    {name = "Rukai Data", url = "/rukaidata"},
    {name = "Canon Collision", url = "/canoncollision"},

    # set newtab to true to make the link open in new tab
    {name = "Github", url = "https://github.com/rukai", newtab = true},
]
